// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence.DBContexts;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240322111040_NibbsPrptyAdded")]
    partial class NibbsPrptyAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Entities.TSAReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AuthorizedDate")
                        .HasColumnType("Date");

                    b.Property<string>("Authorizedby")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("AuthorizerComment")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("BankBranchId")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("BankId")
                        .HasColumnType("varchar(3)");

                    b.Property<string>("BatchId")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("BranchPhoneNumber")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Bvn")
                        .HasColumnType("varchar(11)");

                    b.Property<string>("CbnAcct")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Channel")
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("CollectedAmount")
                        .HasColumnType("DECIMAL(25,2)");

                    b.Property<string>("ConfigId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .HasColumnType("varchar(3)");

                    b.Property<string>("CustomerAccount")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CustomerEmail")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CustomerName")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("CustomerPhoneNumber")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("CustomerTin")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateAdded")
                        .HasColumnType("DateTime2");

                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("DateTime2");

                    b.Property<DateTime?>("DateSentToNibbs")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Fee")
                        .HasColumnType("DECIMAL(25,2)");

                    b.Property<string>("FeedType")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("GifmisCode")
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("InitiatedDate")
                        .HasColumnType("Date");

                    b.Property<string>("Initiatedby")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("InitiatorBranch")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("IsAuthorized")
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsRejected")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSuperAuthorized")
                        .HasColumnType("Bit");

                    b.Property<bool?>("IsSuperRejected")
                        .HasColumnType("bit");

                    b.Property<string>("ItemCode")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ItemName")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LocationCode")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("LocationName")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MdaCode")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MdaName")
                        .HasColumnType("varchar(max)");

                    b.Property<string>("NarrationDescription")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NibbsStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payer")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PsspCode")
                        .HasColumnType("varchar(20)");

                    b.Property<string>("PsspName")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Rejectedby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RejectionDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("RemittedAmount")
                        .HasColumnType("DECIMAL(25,2)");

                    b.Property<string>("RequestId")
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("RequestedAmount")
                        .HasColumnType("DECIMAL(25,2)");

                    b.Property<int?>("SessionId")
                        .HasColumnType("Int");

                    b.Property<string>("SettlementRef")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("StatusCode")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("StatusDescription")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("SuperAuthorizedDate")
                        .HasColumnType("Date");

                    b.Property<string>("SuperAuthorizedby")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SuperAuthorizerComment")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SuperRejectedby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SuperRejectionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransmittedDate")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TsaPcCodename")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TsaPcCoderef")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UniqueReference")
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("ValueDate")
                        .HasColumnType("Date");

                    b.Property<string>("payColDate")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TSAReports");
                });
#pragma warning restore 612, 618
        }
    }
}
